FROM node:20-bullseye

WORKDIR /workspace/radisist/radisist-fixed/radisist-fixed

COPY radisist/radisist-fixed/radisist-fixed/package.json ./

RUN npm install

COPY radisist/radisist-fixed/radisist-fixed ./

EXPOSE 7005

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "7005"]
