FROM node:20-bullseye

WORKDIR /workspace/radisist/radisist-frontend

COPY radisist/radisist-frontend/package.json ./

RUN npm install

COPY radisist/radisist-frontend ./

EXPOSE 7005

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "7005"]
