# Generated by Django 6.0 on 2026-01-04 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="scans/%Y/%m/%d/")),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("MRI", "MRI"),
                            ("CT", "CT Scan"),
                            ("XRAY", "X-Ray"),
                            ("MAMMOGRAM", "Mammogram"),
                            ("OTHER", "Other"),
                        ],
                        default="MAMMOGRAM",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ai_generated", models.BooleanField(default=False)),
                (
                    "ai_predicted_class",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ai_confidence", models.FloatField(blank=True, null=True)),
                ("ai_benign_prob", models.FloatField(blank=True, null=True)),
                ("ai_malignant_prob", models.FloatField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="users.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Full medical report")),
                (
                    "impression",
                    models.TextField(blank=True, help_text="Summary of findings"),
                ),
                ("is_final", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "radiologist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="users.radiologist",
                    ),
                ),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="radiology.scan",
                    ),
                ),
            ],
        ),
    ]
