# Generated by Django 6.0 on 2026-04-26 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='report_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='structured_report',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='analysis_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scan',
            name='audit_trail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='classification_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='disease_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scan',
            name='routed_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='routed_modality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scan',
            name='routing_top3',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scan',
            name='segmentation_overlay_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='segmentation_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='xai_heatmap_base64',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ScanCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scan_crops/%Y/%m/%d/')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='radiology.scan')),
            ],
        ),
    ]
